Project=frontend
GSG-K3/ca-application-website pull request #122
Opened 2020-06-14 12:11 UTC by karmelyoei

2020-06-16 09:04 UTC, DuaaH requested changes

2020-06-16 09:04 UTC, DuaaH commented on client/src/screens/Projects/index.js
> +		else if (id === 4) this.props.history.push('/user/:userId/projects');
you should put userId as a variable in the link depends on the id of the user, ex: ${userId}

2020-06-16 09:33 UTC, karmelyoei commented on client/src/screens/Projects/index.js
> +		else if (id === 4) this.props.history.push('/user/:userId/projects');
yes I have fixed this at the last push yesterday at the last push

2020-06-16 09:58 UTC, DuaaH commented
edit CSS properties for a collapsible button to avoid white page

2020-06-16 11:19 UTC, DuaaH commented on client/src/components/ProjectsTextfields/index.js
> +			.then((data) => {
could you use destruction ({data}) to the data to avoid recursion like that data.data

2020-06-16 11:40 UTC, DuaaH commented on server/controllers/projects.js
> +	const user = req.body;
make sure the userId is a number not string, I see it receives in the server as a string "userID" it should be a number

2020-06-16 11:41 UTC, DuaaH commented on server/database/queries/accounts.js
> +			'Insert INTO account (user_id,github_link, freecodecamp_link, codewars_link)  VALUES($1,$2,$3,$4);',
this query doesn't work, please make sure about the columns in the database

2020-06-16 11:42 UTC, DuaaH commented on client/src/components/ProjectsTextfields/index.js
> +		console.log(this.props);
delete console.log

2020-06-16 11:44 UTC, DuaaH commented on client/src/components/ProjectsTextfields/index.js
> +						style={{ margin: 8, width: '70% ' }}
you can write the styles in a separate file

2020-06-16 11:47 UTC, DuaaH commented on client/src/screens/Profile/index.js
> +		else if (id === 4) this.props.history.push(`/user/:${userId}/projects`);
delete : from the endpoints

2020-06-16 11:53 UTC, DuaaH commented on client/src/components/ProjectsTextfields/index.js
> +		event.preventDefault();
write this statement at the beginning of the function

2020-06-17 13:04 UTC, karmelyoei commented
@DuaaH if you wanna do the merge Please merge this PR and then the profile PRS

2020-06-23 10:42 UTC, merged