Testing
GSG-K3/ca-application-website pull request #95
Opened 2020-05-12 16:08 UTC by karmelyoei

2020-05-13 16:22 UTC, leggomuhgreggo requested changes
Couple small fixups but looks good!

2020-05-13 16:22 UTC, leggomuhgreggo commented on client/public/index.html
> +>>>>>>> be5d385ac1392f2f4c36b8325002281233f2acd4
Looks like there's some merge artifacts here.

2020-05-13 16:22 UTC, leggomuhgreggo commented on client/src/components/Requirments/index.js
> +					</Grid>
If there's time, I could see refactoring this so it maps over an array with the image paths, and returns the Grid item

2020-05-13 16:22 UTC, leggomuhgreggo commented on client/src/screens/Home/index.js
> +import Requierments from '../../components/Requirments';
Requirements*

2020-05-15 00:32 UTC, RandInaim requested changes

2020-05-15 00:32 UTC, RandInaim commented on client/src/components/Requirments/index.js
> +							<Avatar
there is no need to wrap the avatar inside another div

2020-05-15 00:32 UTC, RandInaim commented on client/src/components/Requirments/index.js
> +							<Avatar
it should be a text positioned on the image.
you better do this in the refactor weeks

2020-05-15 00:32 UTC, RandInaim commented on client/src/App.js
> -					<Route path="/login" exact component={Login} />
please be careful while solving the conflicts .please return it instead of the other path

2020-05-16 20:46 UTC, merged